#!/bin/sh

STATE=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)

if [ "$STATE" == "performance" ]; then
    echo "FAST"
elif [ "$STATE" == "powersave" ]; then
    echo "SLOW"
else
    echo "N/A"
fi
