#!/bin/sh

PROJECT=${1:-BAT@rspective}
NAME=${2:-history}

DIRECTORY="/home/afronski/Repositories/WhiteRookPL/private-notes"
FILE="$DIRECTORY/work/active/$PROJECT/$NAME.org"

pushd $DIRECTORY >/dev/null 2>&1

if [ -f $FILE ]; then
    e $FILE >/dev/null 2>&1

    if [ -n "$(git status --porcelain)" ]; then
        git commit -am "Updating journal for $PROJECT."
        git push
    else
        echo "Nothing to commit."
    fi
else
    echo "No such project."
fi

popd >/dev/null 2>&1
