#!/bin/sh

STATE=$(amixer get Master | grep "Front Left:" | awk '{ print $6; }')

if [ "$STATE" == "[on]" ]; then
    echo "(SOUND)"
elif [ "$STATE" == "[off]" ]; then
    echo "(MUTED)"
else
    echo "N/A"
fi
